### ISSUE TITLE
Running Danswer via the Helm chart requires a specific release name

### ISSUE THREAD

**Issue by artmatsak** [danswer-ai/danswer#1537]
I run Danswer locally via the Helm chart as follows:

```
cd danswer/deployment/kubernetes/charts/danswer-stack
helm install danswer-stack-kn .
```

The `danswer-stack-kn` name cannot be changed because of the following:

1. The Helm chart for Vespa [sets](https://github.com/unoplat/vespa-helm-charts/blob/e7db599f1272d3ff4752298dba1db14d05b70409/charts/vespa/templates/_helpers.tpl#L50) the `app.kubernetes.io/instance` selector label for the service to the release name:

```
{{/*
Selector labels
*/}}
{{- define "vespa.selectorLabels" -}}
app.kubernetes.io/name: {{ include "vespa.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
```

2. Danswer's Helm chart [hardcodes](https://github.com/danswer-ai/danswer/blob/44d57f1b53dce2a9a19a8f0a361c0289f3f9d4c6/deployment/kubernetes/charts/danswer-stack/values.yaml#L303) the `app.kubernetes.io/instance` label for the Vespa pod to `danswer-stack-kn`:

```
  podLabels: 
    app: vespa
    app.kubernetes.io/instance: danswer-stack-kn
    app.kubernetes.io/name: vespa
```

Unless the Helm release is run with the very specific `danswer-stack-kn` name, there's a mismatch between Vespa service selector and pod labels, making the Vespa service inaccessible.

**Comment by wyellink** [comment]
You are correct. I am in the same situation. I have made the following changes to my values file to overwrite the original value:

```yaml
vespa:
  podLabels:
    app.kubernetes.io/instance: your-release-name-or-namespace
```

P.S. There were some changes after the chart's consolidation in commit 026652d82741bd15b90e745ac37de8d80a908982. I recommend taking a look at the new charts at https://github.com/danswer-ai/danswer/tree/main/deployment/helm.
