### ISSUE TITLE
Add support for application inference profile or allow litellm to be configured on main LLM config

### ISSUE THREAD

**Issue by jaysonsantos** [danswer-ai/danswer#4669]
Hi there, is it possible to use an application inference profile on the main "LLM" config on the admin?
I've managed to make it work for search settings because it allows litellm to be used and there I had a config like this:

```yaml
   "model_list":
    - "litellm_params":
        "aws_region_name": "eu-central-1"
        "model": "bedrock/arn:aws:bedrock:eu-central-1::foundation-model/anthropic.claude-3-5-sonnet-202406
20-v1:0"
        "model_id": "arn:aws:bedrock:eu-central-1:999999999:application-inference-profile/AAAAAAAAAAAA"
```

and then i can point to a host where litellm is deployed but for the main config i cannot find an option for that
